### ISSUE TITLE
Config模块设计思路讨论...

### ISSUE THREAD

**Issue by henrylee2cn** [xiaoenai/ants#15]
设计思路整理：

1. 每类微服务的多个节点共享同一份配置信息
2. 使用[etcd](https://github.com/coreos/etcd)作为存储介质
3. 微服务监听etcd中对应配置信息的变动，当发生变动时平滑重启自身
4. 提供API接口，便于读写etcd中的配置信息，后期对接到后台管理中心
5. 配置信息带有版本号控制
6. 微服务中直接import本包提供的读取配置信息的函数，不使用API接口通信

- 配置信息格式

```
key: ANTS-CONF@{service_name}@{version}
value: JSON string
```

- 同步流程：
1. 查询etcd中是否已存在当前配置（用key判断）
2. 如果配置不存在，在分布式锁的前提下注册空配置信息到etcd，同时阻塞本地进程，直到开发者通过配置服务的API将正式配置信息写入etcd，接收到etcd PUT事件，更新本地的配置变量
3. 当前进程获取到正确的配置并正常运行过程中，如收到对应配置信息的etcd PUT事件，则重新加载更新本地的配置变量

**Comment by yangwenmai** [comment]
> 微服务中直接import本包提供的读取配置信息的函数，不使用API接口通信

意思是我们会提供一个工具包，用于从 etcd 中读取配置信息，而不是直接通过 etcd API 去读取配置。
